#!/usr/bin/env python3
"""Render the web server's relay config from _data/monitor.yml.

  python render_nginx.py                 rewrite _monitor/web/evl-monitor*.conf
  python render_nginx.py --check         fail if the committed files are out of date (CI)
  python render_nginx.py --out DIR --resolver 127.0.0.11 --host vm=evl-monitor-agent
                                         a test copy (adds DIR/nginx.conf, a stub server)

Rerun it after changing hosts in _data/monitor.yml, then copy the two files to the
web server (see _monitor/README.md).
"""

from __future__ import annotations

import argparse
import os
import sys

import jinja2

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.normpath(os.path.join(HERE, "..", "web"))
sys.path.insert(0, HERE)

import hosts as hosts_mod

PORT = 9877
RESOLVER = "127.0.0.53"  # systemd-resolved on the Ubuntu web server

STUB = """\
events {}
http {
    include /etc/nginx/conf.d/evl-monitor-http.conf;
    server {
        listen 8080;
        include /etc/nginx/snippets/evl-monitor.conf;
        location / { return 200 "site\\n"; }
    }
}
"""


def render(hosts: list[dict], resolver: str) -> dict[str, str]:
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(os.path.join(WEB, "templates")),
                             undefined=jinja2.StrictUndefined, keep_trailing_newline=True)
    ctx = {"generated_by": "Generated by _monitor/tools/render_nginx.py from _data/monitor.yml. Do not edit.",
           "evl_monitor_port": PORT, "evl_monitor_resolver": resolver, "evl_monitor_live_hosts": hosts}
    return {
        "evl-monitor-http.conf": env.get_template("evl-monitor-http.conf.j2").render(ctx),
        "evl-monitor.conf": env.get_template("evl-monitor.conf.j2").render(ctx),
    }


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out")
    ap.add_argument("--resolver", default=RESOLVER)
    ap.add_argument("--host", action="append", default=[], help="id=fqdn (test copies only)")
    args = ap.parse_args(argv)

    hosts = ([dict(zip(("id", "fqdn"), h.split("=", 1))) for h in args.host]
             if args.host else hosts_mod.live_hosts(hosts_mod.load()))
    files = render(hosts, args.resolver)

    if args.check:
        def current(name: str) -> str | None:
            path = os.path.join(WEB, name)
            if not os.path.exists(path):
                return None
            with open(path) as f:
                return f.read()
        stale = [n for n, text in files.items() if current(n) != text]
        for n in stale:
            print(f"_monitor/web/{n} is out of date: run python _monitor/tools/render_nginx.py")
        return 1 if stale else 0

    if args.out:
        for sub in ("conf.d", "snippets"):
            os.makedirs(os.path.join(args.out, sub), exist_ok=True)
        with open(os.path.join(args.out, "conf.d", "evl-monitor-http.conf"), "w") as f:
            f.write(files["evl-monitor-http.conf"])
        with open(os.path.join(args.out, "snippets", "evl-monitor.conf"), "w") as f:
            f.write(files["evl-monitor.conf"])
        with open(os.path.join(args.out, "nginx.conf"), "w") as f:
            f.write(STUB)
        print(f"test copy with {len(hosts)} hosts in {args.out}")
        return 0

    for n, text in files.items():
        with open(os.path.join(WEB, n), "w") as f:
            f.write(text)
    print(f"wrote _monitor/web/ for {len(hosts)} live hosts: {', '.join(h['id'] for h in hosts)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
