name: Tailscale connectivity test

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to tailnet
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest

      - name: Check connectivity
        run: |
          tailscale status
          tailscale ping --until-direct=false -c 3 www-new